/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.ravin.mensagens;

import java.util.ArrayList;

/**
 *
 * @author frete
 */
public class TelaDadosInvalidos extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TelaDadosInvalidos(ArrayList<String> msg) {
        initComponents();
       
        setarDados.setText("Dados Invalidos \n"+msg.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        setarDados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Dados Incorretos ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 80));

        setarDados.setText("jLabel2");
        getContentPane().add(setarDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 250, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel setarDados;
    // End of variables declaration//GEN-END:variables
}
