/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.view;

import java.util.ArrayList;
import org.example.controller.CardapioController;
import org.example.model.Cardapio;
import org.example.model.Produto;
import org.example.repository.RepositoryCardapio;
import org.ravin.mensagens.MensagensCrud;
import org.ravin.mensagens.TelaDadosInvalidos;
import org.ravin.mensagens.TelaSucesso;

/**
 *
 * @author eliez
 */
public class TelaCadastroCardapio extends javax.swing.JFrame {

    private CardapioController cardapioController;
    private Cardapio cardapio;
    private Produto produto;
    private ArrayList<Produto> listProdutos;
    private ArrayList<String> listErros;
    private MensagensCrud mensagensCrud;
    private RepositoryCardapio repositoryCardapio;
    private TelaSucesso telaSucesso;
    private TelaDadosInvalidos telaDadosInvalidos;

    public TelaCadastroCardapio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 467, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        cardapio = new Cardapio();
        listErros = new ArrayList<>();
        
        
        
        
        cardapioController = new CardapioController();
        listErros = cardapioController.validarDados(cardapio);
        if (listErros.isEmpty()) {
            boolean resultadoUpdate = repositoryCardapio.salvar(cardapio);
            if (resultadoUpdate) {
                telaSucesso = new TelaSucesso("Cadastro realizado");
                telaSucesso.setVisible(true);
                dispose();
            } else {
                telaSucesso = new TelaSucesso("Cadastro não realizado");
                telaSucesso.setVisible(true);
                dispose();
            }
        } else {
            telaDadosInvalidos = new TelaDadosInvalidos(listErros);
            telaDadosInvalidos.setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_btnCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    // End of variables declaration//GEN-END:variables
}
