/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.view;

import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.example.controller.CardapioController;
import org.example.model.Cardapio;
import org.example.model.Produto;
import org.example.repository.RepositoryCardapio;
import org.ravin.mensagens.MensagensCrud;
import org.ravin.mensagens.TelaDadosInvalidos;
import org.ravin.mensagens.TelaSucesso;

/**
 *
 * @author eliez
 */
public class TelaCadastroCardapio extends javax.swing.JFrame {

    private CardapioController cardapioController;
    private Cardapio cardapio;
    private Produto produto;
    private ArrayList<Produto> listProdutos;
    private ArrayList<String> listErros;
    private MensagensCrud mensagensCrud;
    private RepositoryCardapio repositoryCardapio;
    private TelaSucesso telaSucesso;
    private TelaDadosInvalidos telaDadosInvalidos;
    private ArrayList<Produto> produtos ;

    public TelaCadastroCardapio() {
        initComponents();
        produtos = new ArrayList<>();
        produtos.add(new Produto("Produto 1", "Descrição do Produto 1"));
        produtos.add(new Produto("Produto 2", "Descrição do Produto 2"));
        produtos.add(new Produto("Produto 3", "Descrição do Produto 3"));

        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Produto");
        tableModel.addColumn("Observação");

        for (Produto produto : produtos) {
            tableModel.addRow(new Object[]{produto.getNome(), produto.getObservacoes()});

        }

        // Criar a tabela com o modelo definido
        jTable1.setModel(tableModel);
        DefaultTableModel model2 = new DefaultTableModel();
        model2.addColumn("Nome");
        model2.addColumn("Descrição");
        jTable2.setModel(model2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbuttonCadastrarCArdapio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbuttonAdicionarProduto = new javax.swing.JButton();
        jButtonExcluitProduto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbuttonCadastrarCArdapio.setText("Cadastrar Cardapio");
        jbuttonCadastrarCArdapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonCadastrarCArdapioActionPerformed(evt);
            }
        });
        getContentPane().add(jbuttonCadastrarCArdapio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 310, 220, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Produto", "Observação"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 170, -1));

        jLabel1.setText("Tipo de produto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Manter Carpadio");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 330, -1));

        jbuttonAdicionarProduto.setText("Adicionar");
        jbuttonAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonAdicionarProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jbuttonAdicionarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 100, -1));

        jButtonExcluitProduto.setText("Excluir");
        jButtonExcluitProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluitProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluitProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 100, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Produto", "Obervação"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Lista de produtos ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Produtos Adicionados");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, -1, 40));

        jCheckBox1.setText("Disponivel");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 280, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 250, 160, -1));

        jLabel5.setText("Nome Cardapio");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 230, -1, -1));

        jLabel6.setText("DescriCao do produto");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, -1, -1));

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane3.setViewportView(txtDescricao);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, -1, -1));

        jButtonVoltar.setText("Voltar");
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 750, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttonCadastrarCArdapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonCadastrarCArdapioActionPerformed
        cardapio = new Cardapio();
        listErros = new ArrayList<>();

        cardapioController = new CardapioController();
        listErros = cardapioController.validarDados(cardapio);
        if (listErros.isEmpty()) {
            boolean resultadoUpdate = repositoryCardapio.salvar(cardapio);
            if (resultadoUpdate) {
                telaSucesso = new TelaSucesso("Cadastro realizado");
                telaSucesso.setVisible(true);
                dispose();
            } else {
                telaSucesso = new TelaSucesso("Cadastro não realizado");
                telaSucesso.setVisible(true);
                dispose();
            }
        } else {
            telaDadosInvalidos = new TelaDadosInvalidos(listErros);
            telaDadosInvalidos.setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_jbuttonCadastrarCArdapioActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int posicao = jTable1.getSelectedRow();
         if (posicao >= 0 && posicao < produtos.size()) {
               Produto produto = produtos.get(posicao);
               String descricao = produto.getObservacoes();
               txtDescricao.setText(descricao);
               System.out.println(descricao);
         }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbuttonAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonAdicionarProdutoActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();
            String nome = jTable1.getValueAt(selectedRow, 0).toString();
            String descricao = jTable1.getValueAt(selectedRow, 1).toString();
            model2.addRow(new Object[]{nome, descricao});
        }
    }//GEN-LAST:event_jbuttonAdicionarProdutoActionPerformed

    private void jButtonExcluitProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluitProdutoActionPerformed
       int selectedRow = jTable2.getSelectedRow();
                if (selectedRow != -1) {
                    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                    model.removeRow(selectedRow);
                }
    }//GEN-LAST:event_jButtonExcluitProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluitProduto;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbuttonAdicionarProduto;
    private javax.swing.JButton jbuttonCadastrarCArdapio;
    private javax.swing.JTextArea txtDescricao;
    // End of variables declaration//GEN-END:variables
}
